name: "Terraform & Docker Deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        id: tf_apply
        run: |
          terraform init
          terraform apply -auto-approve
          IP=$(terraform output -raw instance_ip | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | head -n 1)
          echo "VM_IP=$IP" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Wait for VM to be ready
        run: sleep 120

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.VM_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            sudo rm -rf AgenticAI-AWS
            git clone https://github.com/${{ github.repository }}.git
            cd AgenticAI-AWS
            sudo docker build -t django-app .
            sudo docker stop django-container || true
            sudo docker rm django-container || true
            sudo docker run -d -p 8000:8000 --name django-container django-app